#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
repo=$PWD
mkdir -p GRUB2/SRC GRUB2/NBP
if [[ ! -f GRUB2/grub-2.04.tar.xz ]]; then
    for base in https://ftp.gnu.org/gnu https://mirrors.kernel.org/gnu https://mirrors.ocf.berkeley.edu/gnu; do
        if curl --fail --location --connect-timeout 15 --max-time 120 --retry 1 \
            "$base/grub/grub-2.04.tar.xz" -o GRUB2/grub-2.04.tar.xz.tmp; then
            mv GRUB2/grub-2.04.tar.xz.tmp GRUB2/grub-2.04.tar.xz
            break
        fi
    done
    test -s GRUB2/grub-2.04.tar.xz
fi
# Record the downloaded source hash in the build log.
sha256sum GRUB2/grub-2.04.tar.xz
tar -xf GRUB2/grub-2.04.tar.xz -C GRUB2/SRC
cp -a GRUB2/MOD_SRC/grub-2.04/. GRUB2/SRC/grub-2.04/
cd GRUB2/SRC/grub-2.04
./autogen.sh
./configure --target=x86_64 --with-platform=efi --prefix="$repo/GRUB2/INSTALL" --disable-werror
make -j"${JOBS:-4}"
bash install.sh uefi
cd "$repo"
rm -rf INSTALL_LOCAL_ESP
mkdir -p INSTALL_LOCAL_ESP/EFI/Ventoy INSTALL_LOCAL_ESP/ventoy-local
# Secure Boot OFF: load the patched GRUB directly, without the upstream shim chain.
cp INSTALL/EFI/BOOT/grubx64_real.efi INSTALL_LOCAL_ESP/EFI/Ventoy/BOOTX64.EFI
cp INSTALL/EFI/BOOT/grubx64_real.efi INSTALL_LOCAL_ESP/EFI/Ventoy/grubx64_real.efi
cp -a INSTALL/grub INSTALL/ventoy INSTALL/tool INSTALL_LOCAL_ESP/ventoy-local/
cp GRUB2/ventoy_esp_bootstrap.cfg INSTALL_LOCAL_ESP/ventoy-local/grub/esp-bootstrap.cfg
# Match upstream ventoy_pack.sh: zh_CN first, then sorted languages and Return.
python3 - <<'PY'
from pathlib import Path

menu = Path("INSTALL/grub/menu")
output = Path("INSTALL_LOCAL_ESP/ventoy-local/grub/menulang.cfg")
entries = [Path("INSTALL/grub/menulang.cfg").read_text(encoding="utf-8")]
languages = [menu / "zh_CN.json"] + sorted(
    path for path in menu.glob("*.json") if path.name != "zh_CN.json"
)
for path in languages:
    # Upstream extracts this field without parsing the entire language file.
    title = next(line for line in path.read_text(encoding="utf-8-sig").splitlines()
                 if "VTLANG_LANGUAGE_NAME" in line).split('"')[3]
    entries.append(
        f'menuentry "{path.stem}  -  {title}" --class=menu_lang_item '
        f'--class=debug_menu_lang --class=F5tool {{\n'
        f'    vt_load_menu_lang {path.stem}\n}}\n'
    )
entries.append('menuentry "$VTLANG_RETURN_PREVIOUS" --class=vtoyret VTOY_RET {\n'
               '        echo "Return ..."\n}\n')
output.write_bytes("".join(entries).encode("utf-8"))
PY
# These runtime archives are generated by upstream ventoy_pack.sh, not tracked.
tar -czf INSTALL_LOCAL_ESP/ventoy-local/grub/menu.tar.gz -C INSTALL/grub ./menu/
tar -czf INSTALL_LOCAL_ESP/ventoy-local/grub/help.tar.gz -C INSTALL/grub ./help/
printf 'VENTOY_LOCAL_ESP_V1\n' > INSTALL_LOCAL_ESP/ventoy-local/ventoy/ventoy.esp.marker
find INSTALL_LOCAL_ESP -type f -print0 | sort -z | xargs -0 sha256sum > local-esp.sha256
printf 'commit=%s\n' "$(git rev-parse HEAD)" > local-esp-build.txt
gcc --version >> local-esp-build.txt
cat /etc/os-release >> local-esp-build.txt
tar -czf ventoy-local-esp-x86_64.tar.gz INSTALL_LOCAL_ESP local-esp.sha256 local-esp-build.txt
